
package HRM;

import java.io.File;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

public class frmLetterOffer extends javax.swing.JFrame {
DbConnection DbConn = new DbConnection();
String GetDesignation, GetDepartment;
    public frmLetterOffer() {
        initComponents();
        DbConn.DoConnect();
        FillTable();
        FillPosition();
        FillGeneratedBy();
        setLocationRelativeTo(null);
        setLocationRelativeTo(null);
        tableOffer.setDefaultEditor(Object.class, null);
        dateStart.setDate(DbConn.DateToday);
        txtName.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {ListenSearch();}

            @Override
            public void removeUpdate(DocumentEvent e) {ListenSearch();}

            @Override
            public void changedUpdate(DocumentEvent e) {ListenSearch();}
        });
    }
    private void ListenSearch(){
        try{
             DbConn.SQLQuery = "Select ca_seqno,ca_name,ca_age,ca_nationality,ca_field,"
                    + "ca_school,ca_position from tblcandidate where ca_name like ?";
            DbConn.pstmt = DbConn.conn.prepareStatement(DbConn.SQLQuery);
            DbConn.pstmt.setString(1, "%"+ txtName.getText()+"%");
            DbConn.rs = DbConn.pstmt.executeQuery();
            tableOffer.setModel(DbUtils.resultSetToTableModel(DbConn.rs));
            DbConn.pstmt.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Live Search");
        }
    }
    private void FillGeneratedBy(){
        cmbProposedBy.removeAllItems();
        try{
            DbConn.pstmt = DbConn.conn.prepareStatement("select em_name from tblemployeeprofile order by em_name");
            DbConn.rs = DbConn.pstmt.executeQuery();
            while (DbConn.rs.next()){
                cmbProposedBy.addItem(DbConn.rs.getString(1));
            }
            DbConn.pstmt.close();
            cmbProposedBy.setSelectedIndex(-1);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Proposed Name Drop Down");
        }
    }
    private void FillPosition(){
        cmbPosition.removeAllItems();
        try{
            DbConn.pstmt = DbConn.conn.prepareStatement("Select po_description from tblposition order by po_description");
            DbConn.rs = DbConn.pstmt.executeQuery();
            while (DbConn.rs.next()){
                cmbPosition.addItem(DbConn.rs.getString(1));
            }
            DbConn.pstmt.close();
            cmbPosition.setSelectedIndex(-1);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Fill Position");
        }
    }
    private void FillTable(){
        try{
            DbConn.SQLQuery = "Select ca_seqno,ca_name,ca_age,ca_nationality,ca_field,"
                    + "ca_school,ca_position from tblcandidate order by ca_seqno";
            DbConn.pstmt = DbConn.conn.prepareStatement(DbConn.SQLQuery);
            DbConn.rs = DbConn.pstmt.executeQuery();
            tableOffer.setModel(DbUtils.resultSetToTableModel(DbConn.rs));
            DbConn.pstmt.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "FillTable");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cmbPosition = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        dateStart = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cmbProposedBy = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableOffer = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(214, 214, 194));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 690, 20));

        jPanel3.setBackground(new java.awt.Color(214, 214, 194));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 153, 153)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Name:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 20));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Amount:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 20));
        jPanel3.add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 200, -1));
        jPanel3.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 580, -1));

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Generated By:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 80, 20));

        cmbPosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(cmbPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 200, -1));

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Start Date:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 80, 20));

        dateStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                dateStartMouseReleased(evt);
            }
        });
        jPanel3.add(dateStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 200, 30));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("ID:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 50, 20));
        jPanel3.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 270, -1));

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Position:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 80, 20));

        cmbProposedBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(cmbProposedBy, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 270, -1));

        jButton1.setBackground(new java.awt.Color(92, 184, 92));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Generate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 690, 180));

        tableOffer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableOffer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableOfferMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableOffer);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 690, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dateStartMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateStartMouseReleased

    }//GEN-LAST:event_dateStartMouseReleased

    private void tableOfferMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableOfferMouseClicked
        int row = tableOffer.getSelectedRow();
        int ba = tableOffer.convertRowIndexToModel(row);
        
        txtName.setText(tableOffer.getModel().getValueAt(ba, 1).toString());
        cmbPosition.setSelectedItem(tableOffer.getModel().getValueAt(ba, 6).toString());
       
    }//GEN-LAST:event_tableOfferMouseClicked
    private void GetTitle(){
        try{
            DbConn.pstmt = DbConn.conn.prepareStatement("select em_department,em_designation from tblemployeeprofile order by em_name");
            DbConn.rs = DbConn.pstmt.executeQuery();
            if (DbConn.rs.next()){
                GetDepartment = DbConn.rs.getString(1);
                GetDesignation = DbConn.rs.getString(2);
            }
            DbConn.pstmt.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Title Get");
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int itemSelect = JOptionPane.showConfirmDialog(this, "This will update the candidate status to Job Offer Generated. Proceed?","Letter of Offer",JOptionPane.YES_NO_OPTION);
        if (itemSelect == JOptionPane.YES_OPTION){
            GetTitle();
            
            Map param = new HashMap();
            param.put("CandidateName", txtName.getText() + ",");
            param.put("GeneratedBy", cmbProposedBy.getSelectedItem().toString());
            param.put("StartDate", String.valueOf(DbConn.sdfDateDisplay.format(dateStart.getDate())));
            param.put("Position", cmbPosition.getSelectedItem().toString());
            param.put("SalaryAmount", txtAmount.getText());
            param.put("TitleDepartment", GetDepartment);
            param.put("TitleSignature", GetDesignation);
            try{
                //update status to Job Offer Generated
                DbConn.pstmt = DbConn.conn.prepareStatement("update tblcandidate set ca_status=? where ca_seqno=?");
                DbConn.pstmt.setString(1, "Job Offer Generated");
                DbConn.pstmt.setString(2, tableOffer.getValueAt(0, 0).toString());
                DbConn.pstmt.executeUpdate();
                DbConn.pstmt.close();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            try{                
                //view letter offer
                DbConn.conn.close();
                Class.forName("com.mysql.jdbc.Driver");
                DbConn.conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbeshr?autoReconnect=true","root","root");
                JasperDesign jd = JRXmlLoader.load(new File("src\\HRReports\\reportLetterOffer.jrxml"));
                JasperReport jr = JasperCompileManager.compileReport(jd);
                JasperPrint jp = JasperFillManager.fillReport(jr, param,DbConn.conn);
                JasperViewer.viewReport(jp,false);

            }catch(ClassNotFoundException | SQLException | JRException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLetterOffer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLetterOffer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLetterOffer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLetterOffer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLetterOffer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbPosition;
    private javax.swing.JComboBox<String> cmbProposedBy;
    private com.toedter.calendar.JDateChooser dateStart;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tableOffer;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
